### ISSUE TITLE
cloning

### ISSUE THREAD

**Issue by spade101** [MuhammadSabah/Food-Recipe-FinalProject#1]
can i edit this project and make it my own and publish it on google play
but why cant i see the android file on project menu dropdown is this restricted
i like your code its clean and i can understand some of its code im new to coding
are you related to flutter apprentice book

**Comment by MuhammadSabah** [comment]
Thank you, but NO, I'm sorry you can't, it's my project and I don't want it to be published on the play store.

**Comment by spade101** [comment]
ok and thanks i learn a lot in this project. did you based it on fooderlich book i think theres similararity on the code

**Comment by MuhammadSabah** [comment]
Appreciate it. I've read the book before so yes there is some similarity.

**Comment by spade101** [comment]
> Appreciate it. I've read the book before so yes there is some simila
can ask whats if this is the MVVM structure i really like the code

**Comment by MuhammadSabah** [comment]
It's not an MVVM structure. I actually just searched on Google and found this pattern, I'm not sure what the pattern was called but it was  good. So I decided to use it.

**Comment by spade101** [comment]
ok. thanks
