### ISSUE TITLE
problem while doing pub get

### ISSUE THREAD

**Issue by tilakpatel22** [MuhammadSabah/Food-Recipe-FinalProject#2]
![Screenshot 2023-04-19 143243](https://user-images.githubusercontent.com/66294702/233025044-dd6f1123-f38e-4d9d-9e35-f7b3b8647704.png)
any solution for this ?

**Comment by MuhammadSabah** [comment]
I've tried it multiple times but there was no issue. Are you using the latest version for Flutter and Dart?
